[project]
name = "suso-gpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bs4>=0.0.2",
    "chromadb==1.5.9",
    "docx2txt==0.9",
    "fastapi==0.136.3",
    "ipykernel>=7.3.0",
    "jinja2==3.1.6",
    "langchain==1.3.2",
    "langchain-chroma==1.1.0",
    "langchain-community>=0.4.2",
    "langchain-core==1.4.0",
    "langchain-openai>=1.2.2",
    "langchain-tavily==0.2.18",
    "langchain-text-splitters==1.1.2",
    "langgraph==1.2.2",
    "langgraph-checkpoint-sqlite==3.1.0",
    "mem0ai>=2.0.17",
    "openai>=2.53.0",
    "pandas>=3.0.5",
    "pymupdf>=1.28.2",
    "pypdf==6.12.2",
    "pytesseract>=0.3.13",
    "python-dotenv==1.2.2",
    "python-multipart==0.0.29",
    "sqlalchemy==2.0.50",
    "tavily-python==0.7.24",
    "unstructured>=0.25.2",
    "uvicorn==0.48.0",
]
