import type { Meta, StoryObj } from "@storybook/react";
import { Button } from "@/ui/button";
import { WorkspaceContextBar, WorkspaceCommandBar, CanvasWorkspaceShell, WorkspaceInspector, WorkspaceDisclosure } from "./CanvasWorkspace";

const meta = { title: "Design System/Workspace hierarchy", component: CanvasWorkspaceShell, parameters: { layout: "fullscreen" }, decorators: [(Story) => <div className="flex h-[800px] flex-col bg-background p-3"><WorkspaceContextBar title="Processo dimostrativo" actions={<Button variant="outline" size="sm">AS-IS · Esecuzione 1</Button>} /><div className="min-h-0 flex-1 pt-2"><Story /></div></div>] } satisfies Meta<typeof CanvasWorkspaceShell>;
export default meta;
type Story = StoryObj<typeof meta>;
const commands = <WorkspaceCommandBar label="Strumenti"><Button size="sm" variant="secondary">Osserva</Button><Button size="sm" variant="ghost">Scenario</Button><Button size="sm" variant="ghost">Confronto</Button><div className="ml-auto flex gap-2"><WorkspaceDisclosure label="Metriche"><p>Metriche dello stesso istante osservato.</p></WorkspaceDisclosure><Button size="sm" variant="outline">Aggiungi elemento</Button></div></WorkspaceCommandBar>;
export const CanvasFirst: Story = { args: { label: "Studio", resizeLabel: "Ridimensiona area canvas", resizeHint: "Frecce per ridimensionare, Home per ripristinare", commands, children: <div className="flex h-full items-center justify-center bg-muted text-muted-foreground">Canvas: processo, metriche e grafici</div>, playback: <div className="flex items-center gap-3 p-2"><Button size="sm">Riproduci</Button><span className="text-xs">Tempo osservato · 10:30</span></div> } };
export const WithInspector: Story = { args: { ...CanvasFirst.args, inspector: <WorkspaceInspector resizeLabel="Ridimensiona pannello di dettagli" initialWidth={320} label="Dettagli" title="Attività selezionata" scope="Tempo osservato" closeLabel="Chiudi dettagli" onClose={() => {}} className="w-80"><p className="text-sm">L'ispettore usa un binario laterale; il canvas conserva il proprio spazio.</p></WorkspaceInspector> } };
